Add macOS support 5

diff --git a/.github/workflows/functional-tests-local.yml b/.github/workflows/functional-tests-local.yml
--- a/.github/workflows/functional-tests-local.yml
+++ b/.github/workflows/functional-tests-local.yml
@@ -15,8 +15,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        #        os: ["ubuntu", "macos", "windows"]
-        os: ["windows"]
+        os: ["ubuntu", "macos", "windows"]
     runs-on: ${{ matrix.os }}-latest
     steps:
       - name: Checkout ${{ github.repository }}
@@ -24,7 +23,16 @@ jobs:
       - name: Setup Prolog
         id: setup-prolog
         uses: ./
+        continue-on-error: true
+      - name: Validate failure
+        if: ${{ matrix.os == 'windows' }}
+        run: |
+          if [ "${{ steps.setup-prolog.outcome }}" != "failure" ]; then
+            echo "::error title=Test failed::Setting up Prolog was expected to fail"
+            exit 1
+          fi
       - name: Validate script
+        if: ${{ matrix.os != 'windows' }}
         run: |
           echo "main :- write('Hello World!'), nl." > hello-world.pl
           [ "$(swipl -s hello-world.pl -g main -t halt)" = "Hello World!" ] || exit 1;
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,6 +15,12 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Fail
+      if: ${{ runner.os == 'Windows' }}
+      run: |
+        echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
+      shell: sh
     - name: Validate inputs
       id: validate-inputs
       env:
